## Reduce sentence to report labels

In [1]:
import numpy as np

In [30]:
support_mask = np.zeros(n_diseases)
if support_idxs is not None:
    support_mask[support_idxs] = 1

support_mask

array([0., 1., 0., 0.])

In [39]:
np.ma

<module 'numpy.ma' from '/home/pdpino/medical-ai/pyenv3.6/lib/python3.6/site-packages/numpy/ma/__init__.py'>

In [48]:
arr = np.ma.array([0, 3, 0], mask=[0, 0, 0])

In [49]:
np.ma.all((arr == 0) | (arr == -2))

False

In [33]:
np.all((arr == 0) | (arr == -2))

False

In [65]:
no_finding_idx = 0
support_idxs = 1 # [1, 2] # support devices, that kind of stuff
n_diseases = 4

In [77]:
def _reduce_report(report):
    # all_labels = np.array([self._labels_by_sentence[sentence] for sentence in report])
    all_labels = np.array(report)
    # shape: n_sentences, n_diseases

    reduced_labels = all_labels.max(axis=0)
    # shape: n_diseases

    if no_finding_idx is None:
        return reduced_labels
    
    ignore_mask = np.zeros(n_diseases)
    ignore_mask[no_finding_idx] = 1
    if support_idxs is not None:
        ignore_mask[support_idxs] = 1
    disease_labels = np.ma.array(reduced_labels, mask=ignore_mask)

    no_diseases = np.ma.all((disease_labels == 0) | (disease_labels == -2))
    
    reduced_labels[no_finding_idx] = int(no_diseases)
    
    return reduced_labels

In [8]:
import pandas as pd

In [9]:
%run ../datasets/iu_xray.py

In [11]:
fpath = os.path.join(DATASET_DIR, 'reports', 'reports_with_chexpert_labels.csv')
df = pd.read_csv(fpath, index_col=0)
df.head()

Reports  No Finding  \
0  the cardiac silhouette and mediastinum size ar...         1.0   
1  the cardiomediastinal silhouette is within nor...        -2.0   
2  both lungs are clear and expanded . heart and ...         1.0   
3  there is xxxx increased opacity within the rig...        -2.0   
4  interstitial markings are diffusely prominent ...        -2.0   

   Enlarged Cardiomediastinum  Cardiomegaly  Lung Lesion  Lung Opacity  Edema  \
0                         0.0           0.0         -2.0          -2.0    0.0   
1                         0.0          -2.0         -2.0           0.0   -2.0   
2                         0.0          -2.0         -2.0          -2.0   -2.0   
3                        -2.0           0.0         -1.0           1.0   -2.0   
4                        -2.0           0.0         -2.0           1.0   -2.0   

   Consolidation  Pneumonia  Atelectasis  Pneumothorax  Pleural Effusion  \
0            0.0       -2.0         -2.0           0.0               0.0   
1           -2.0       -2.0         -2.0           0.0               0.0   
2           -2.0       -2.0         -2.0          -2.0              -2.0   
3           -1.0       -2.0         -1.0           0.0               0.0   
4           -2.0       -2.0         -2.0          -2.0              -2.0   

   Pleural Other  Fracture  Support Devices  filename  
0           -2.0      -2.0             -2.0     1.xml  
1           -2.0      -2.0             -2.0    10.xml  
2           -2.0      -2.0             -2.0   100.xml  
3           -2.0      -2.0             -2.0  1000.xml  
4           -2.0      -2.0             -2.0  1001.xml

In [14]:
from collections import Counter

In [15]:
Counter(df['No Finding'])

Counter({1.0: 1502, -2.0: 2324})

In [13]:
df['No Finding'].describe()

count    3826.000000
mean       -0.822269
std         1.465163
min        -2.000000
25%        -2.000000
50%        -2.000000
75%         1.000000
max         1.000000
Name: No Finding, dtype: float64

## Torch Nan

In [30]:
import torch

In [31]:
# %run ../utils/common.py
%run ../losses/out_of_target.py

In [36]:
a = torch.rand(2, 2)
b = (torch.rand(2, 2) > 0.5).long()
a = (b).float()
a, b

(tensor([[0., 1.],
         [0., 1.]]),
 tensor([[0, 1],
         [0, 1]]))

In [37]:
loss = OutOfTargetSumLoss(eps=1e-7)
loss(a, b)

tensor(-2.3842e-07)

## Regex

In [1]:
import re

In [32]:
loss_regex = re.compile(r'(\w+)_loss\Z')

In [33]:
def f(name):
    found = loss_regex.search(name)
    if found:
        captured = found.group(1)
        return f'Loss_{captured}'
    
    return name

In [37]:
f('asdf_loss')

'Loss_asdf'

## grad

In [13]:
import torch

In [2]:
torch.set_grad_enabled(False)

In [4]:
a = torch.tensor([1, 2, 3.0], requires_grad=True)
a

tensor([1., 2., 3.], requires_grad=True)

In [6]:
b = 2 * a
b

tensor([2., 4., 6.])

In [56]:
b.requires_grad

False

## Autograd

In [76]:
import torch
from torch import nn

In [114]:
class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()

        # self.weights = torch.rand(2, 2, requires_grad=True)
        self.linear1 = nn.Linear(2, 2)
        self.linear2 = nn.Linear(2, 2)
    
    def forward(self, x):
        x = self.linear1(x)
        x = self.linear2(x)
        return torch.softmax(x, dim=1)

In [150]:
model = SimpleModel()

In [151]:
gt = torch.tensor([1, 0]).unsqueeze(0)
x = torch.rand(2).unsqueeze(0)
out = model(x)
gt, x, out

(tensor([[1, 0]]),
 tensor([[0.1570, 0.1996]]),
 tensor([[0.5020, 0.4980]], grad_fn=<SoftmaxBackward>))

In [152]:
model.linear1.weight, model.linear2.weight

(Parameter containing:
 tensor([[-0.1388, -0.6964],
         [-0.1724, -0.3032]], requires_grad=True),
 Parameter containing:
 tensor([[ 0.4651,  0.5530],
         [-0.7043,  0.5696]], requires_grad=True))

In [153]:
r = torch.autograd.grad(out, model.linear2.weight, gt, only_inputs=False, create_graph=True)[0]
r

/home/pdpino/medical-ai/pyenv3.6/lib/python3.6/site-packages/torch/autograd/__init__.py:192: UserWarning: only_inputs argument is deprecated and is ignored now (defaults to True). To accumulate gradient for other parts of the graph, please use torch.autograd.backward.
  warnings.warn("only_inputs argument is deprecated and is ignored now "


tensor([[ 0.1351, -0.1982],
        [-0.1351,  0.1982]], grad_fn=<TBackward>)

In [149]:
model.linear2.weight.grad, out.grad

/home/pdpino/medical-ai/pyenv3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.


(None, None)

In [137]:
gt_map = torch.ones(r.size())
loss = (r - gt_map).sum()
loss.backward()

In [65]:
loss = (gt - out)
loss

tensor([0.5733, 0.5500], grad_fn=<SubBackward0>)

In [66]:
out.retain_grad()

In [69]:
model.weights.grad, x.grad, out.grad

(tensor([[-0.3334, -0.2032],
         [-0.3334, -0.2032]]),
 None,
 tensor([-1., -1.]))

In [68]:
loss.backward(torch.ones(out.size()), create_graph=True)

## Shared interest data files

In [1]:
import torch
import json

In [8]:
fpath = '~/software/shared-interest/data/examples/data_cxr14.json' # dogs

In [9]:
with open(fpath) as f:
    data = json.load(f)
len(data)

9

In [10]:
data.keys()

dict_keys(['fname', 'image', 'bbox', 'saliency', 'label', 'prediction', 'ground_truth_coverage', 'explanation_coverage', 'iou'])

In [13]:
set(type(a) for a in data['label'].values())

{str}

In [14]:
len(data['label'])

5045

## Debug MedicalLabelerCorrectness

In [6]:
import numpy as np
import torch
from torch.nn.utils.rnn import pad_sequence

In [7]:
%run ../metrics/report_generation/labeler_correctness/cache.py
%run ../metrics/report_generation/labeler_correctness/light_labeler.py
%run ../metrics/report_generation/labeler_correctness/__init__.py

In [8]:
%run ../datasets/vocab/__init__.py

In [9]:
%run ../datasets/iu_xray.py
%run ../utils/nlp.py

In [10]:
dataset = IUXRayDataset('all')
len(dataset)

7426

In [11]:
report_reader = ReportReader(dataset.get_vocab())

In [12]:
chexpert_labeler = ChexpertLightLabeler(dataset.get_vocab())
chexpert_labeler

In [15]:
reports = pad_sequence([
    torch.tensor(dataset[idx+2].report)
    for idx in [100, 200, 300, 400]
], batch_first=True)
reports

tensor([[ 32,  11,  50,   4,  52,  10,  13,   4,  17,  28,   4,   0,   0,   0,
           0],
        [ 40,  13,  52,  10,   4, 151,  43, 571,   4,  32,  11,  50,   4,   0,
           0],
        [ 52,  10,  16,  13,   8,  32,  11,  50,   4,  17,  27,  23, 563,   4,
           0],
        [ 52,  10,  13,   8,  32,  11,  50,   4, 300, 727,  63, 135,  68, 312,
           4]])

In [9]:
metric = MedicalLabelerCorrectness(chexpert_labeler)
metric

In [18]:
metric.reset()
metric.update((reports, reports))
metric.compute()

{'acc': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'prec': array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]),
 'recall': array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]),
 'spec': array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'npv': array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])}

In [11]:
[report_reader.idx_to_text(r) for r in reports]

['xxxx change . no active cardiopulmonary disease . thoracolumbar scoliosis . PAD PAD PAD PAD',
 'chest . no active disease . right shoulder . healing scapular fracture . PAD PAD',
 'the cardiac contours are normal . the lungs are clear . thoracic spondylosis . PAD',
 'heart size is normal and the lungs are clear . no nodules or masses .']